### ISSUE TITLE
Remove () from filename

### ISSUE THREAD

**Issue by neoneye** [George-J-E/HidingViews#2]
The file named "View-hidden().swift" may cause problems.

I wrote a file manager 10 years ago and the () characters are especially terrible in file names.

Sorry about this. I recommend removing the ().

**Comment by GeorgeElsham** [comment]
Fixed. Sorry for the long delay, I don't use GitHub often and this notification was sent to spam email. Updated, thanks!

**Comment by KyNorthstar** [comment]
A file manager which doesn't allow certain characters in file names (which are OK in the filesystem) I just poorly-written software. It's no reason to change the files' names.

**Comment by neoneye** [comment]
@BenLeggiero the operating systems itself, doesn't allow any character in filenames. Further more exotic filenames has to given a special treatment in scripts, and apps, to deal with all kinds of special characters, such as backslash, forward slash, emojis. Few tools do that correctly.

When I did [my file manager](https://github.com/neoneye/newton-commander), I analyzed how well other tools are at copying files, and it turned out that they all do a rather poor job at preserving data. My filemanager passed all my tests, so I think I did an ok job at dealing with special characters and metadata.
https://www.flickr.com/photos/12739382@N04/4122461472/

I disagree with you that my filemanager was poorly written software.

**Comment by KyNorthstar** [comment]
I'm not sure what OS you're using, @neoneye , but I just tried on macOS 10.15 and Ubuntu 18.04, and both were just fine naming a file `sample().swift`. Tools which don't handle this are poorly-made tools. I know this, as a toolmaker, myself. It's trivial to handle filenames with these notable characters (for instance, in a shell script, `"${filePath}" instead of just `$filePath`).

Thanks for the link! I'll try it out 😄
I'll also leave any feedback I have on its GitHub page so we don't continue to clog this one. But I do assert that a file manager's first priority should be being a complete frontend to the filesystems it supports, including all the odd filenames that might entail. I'm glad you and I both learned this lesson, and I'm fascinated how we learned it in different ways 🙂
