### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Adamekka** [George-J-E/HidingViews#6]
Hello, I would like to use this repo as a dependency on a commercial app that will be on the App Store, but Apple is strict, so if you would consider adding an MIT license.

**Comment by Adamekka** [comment]
I thought this was a complicated project, but it's few lines, so I'll just copy it if you don't mind

**Comment by GeorgeElsham** [comment]
Completely fine to copy the source and use & modify however you'd like (no warranties blah blah blah). To be honest - this should have just been a gist rather than a repo, but too late now. FWIW I don't even use this stuff in my own code because I actually think it abstracts away so little complexity, and I wrote this before I could realise that it was probably a mistake.

**Comment by KyNorthstar** [comment]
@GeorgeElsham 
Sounds like the MIT license fits!

**Comment by Adamekka** [comment]
> @GeorgeElsham Sounds like the MIT license fits!

it's like 5 lines of code if you need the functionality, steal it

**Comment by KyNorthstar** [comment]
Just for funsies, I created PR #7 to address this
